// @generated by packages/gambit/packages/gambit-simulator/simulator-ui/scripts/generate_workspace_build_tab_live_subscription_query.ts
export const WORKSPACE_BUILD_TAB_LIVE_WRITE_ROOT_KEY = "workspace____id___v_workspaceId" as const;

export const WORKSPACE_BUILD_TAB_LIVE_SUBSCRIPTION_QUERY = "subscription WorkspaceBuildTabLiveSubscription($workspaceId: ID!, $fromOffset: Int) {\n  workspaceBuildLive(workspaceId: $workspaceId, fromOffset: $fromOffset) {\n    cursor\n    sourceOffset\n    occurredAt\n    node {\n      id\n      files____first___l_200: files(first: 200) {\n        edges {\n          node {\n            id\n            content\n            modifiedAt\n            path\n            size\n          }\n        }\n      }\n    }\n  }\n}\n";

export default WORKSPACE_BUILD_TAB_LIVE_SUBSCRIPTION_QUERY;
