import type { EagerReaderArtifact, ReaderAst } from '@isograph/react';
import { Query__EntrypointWorkspaceVerifyLiveWrite__param } from './param_type.ts';
import { Query__EntrypointWorkspaceVerifyLiveWrite__output_type } from './output_type.ts';
import { EntrypointWorkspaceVerifyLiveWrite as resolver } from '../../../../isograph/entrypoints/EntrypointWorkspaceVerifyLiveWrite.tsx';

const readerAst: ReaderAst<Query__EntrypointWorkspaceVerifyLiveWrite__param> = [
  {
    kind: "Linked",
    fieldName: "workspace",
    alias: null,
    arguments: [
      [
        "id",
        { kind: "Variable", name: "workspaceId" },
      ],
    ],
    condition: null,
    isUpdatable: false,
    refetchQueryIndex: null,
    selections: [
      {
        kind: "Scalar",
        fieldName: "id",
        alias: null,
        arguments: null,
        isUpdatable: false,
      },
      {
        kind: "Linked",
        fieldName: "scenarioDecks",
        alias: null,
        arguments: null,
        condition: null,
        isUpdatable: false,
        refetchQueryIndex: null,
        selections: [
          {
            kind: "Scalar",
            fieldName: "id",
            alias: null,
            arguments: null,
            isUpdatable: false,
          },
          {
            kind: "Scalar",
            fieldName: "label",
            alias: null,
            arguments: null,
            isUpdatable: false,
          },
          {
            kind: "Scalar",
            fieldName: "description",
            alias: null,
            arguments: null,
            isUpdatable: false,
          },
          {
            kind: "Scalar",
            fieldName: "path",
            alias: null,
            arguments: null,
            isUpdatable: false,
          },
        ],
      },
      {
        kind: "Linked",
        fieldName: "verification",
        alias: null,
        arguments: null,
        condition: null,
        isUpdatable: false,
        refetchQueryIndex: null,
        selections: [
          {
            kind: "Linked",
            fieldName: "graderDecks",
            alias: null,
            arguments: [
              [
                "first",
                { kind: "Literal", value: 50 },
              ],
            ],
            condition: null,
            isUpdatable: false,
            refetchQueryIndex: null,
            selections: [
              {
                kind: "Linked",
                fieldName: "edges",
                alias: null,
                arguments: null,
                condition: null,
                isUpdatable: false,
                refetchQueryIndex: null,
                selections: [
                  {
                    kind: "Linked",
                    fieldName: "node",
                    alias: null,
                    arguments: null,
                    condition: null,
                    isUpdatable: false,
                    refetchQueryIndex: null,
                    selections: [
                      {
                        kind: "Scalar",
                        fieldName: "id",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "label",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "description",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "path",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            kind: "Linked",
            fieldName: "batches",
            alias: null,
            arguments: [
              [
                "first",
                { kind: "Literal", value: 50 },
              ],
            ],
            condition: null,
            isUpdatable: false,
            refetchQueryIndex: null,
            selections: [
              {
                kind: "Linked",
                fieldName: "edges",
                alias: null,
                arguments: null,
                condition: null,
                isUpdatable: false,
                refetchQueryIndex: null,
                selections: [
                  {
                    kind: "Linked",
                    fieldName: "node",
                    alias: null,
                    arguments: null,
                    condition: null,
                    isUpdatable: false,
                    refetchQueryIndex: null,
                    selections: [
                      {
                        kind: "Scalar",
                        fieldName: "id",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "workspaceId",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "scenarioDeckId",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "graderId",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "scenarioRuns",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "graderRepeatsPerScenario",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "status",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "startedAt",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "finishedAt",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "requested",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "active",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "completed",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "failed",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "scenarioRunsCompleted",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Scalar",
                        fieldName: "scenarioRunsFailed",
                        alias: null,
                        arguments: null,
                        isUpdatable: false,
                      },
                      {
                        kind: "Linked",
                        fieldName: "requests",
                        alias: null,
                        arguments: [
                          [
                            "first",
                            { kind: "Literal", value: 200 },
                          ],
                        ],
                        condition: null,
                        isUpdatable: false,
                        refetchQueryIndex: null,
                        selections: [
                          {
                            kind: "Linked",
                            fieldName: "edges",
                            alias: null,
                            arguments: null,
                            condition: null,
                            isUpdatable: false,
                            refetchQueryIndex: null,
                            selections: [
                              {
                                kind: "Linked",
                                fieldName: "node",
                                alias: null,
                                arguments: null,
                                condition: null,
                                isUpdatable: false,
                                refetchQueryIndex: null,
                                selections: [
                                  {
                                    kind: "Scalar",
                                    fieldName: "id",
                                    alias: null,
                                    arguments: null,
                                    isUpdatable: false,
                                  },
                                  {
                                    kind: "Scalar",
                                    fieldName: "scenarioRunId",
                                    alias: null,
                                    arguments: null,
                                    isUpdatable: false,
                                  },
                                  {
                                    kind: "Scalar",
                                    fieldName: "status",
                                    alias: null,
                                    arguments: null,
                                    isUpdatable: false,
                                  },
                                  {
                                    kind: "Scalar",
                                    fieldName: "runId",
                                    alias: null,
                                    arguments: null,
                                    isUpdatable: false,
                                  },
                                  {
                                    kind: "Scalar",
                                    fieldName: "error",
                                    alias: null,
                                    arguments: null,
                                    isUpdatable: false,
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                      {
                        kind: "Linked",
                        fieldName: "metrics",
                        alias: null,
                        arguments: null,
                        condition: null,
                        isUpdatable: false,
                        refetchQueryIndex: null,
                        selections: [
                          {
                            kind: "Scalar",
                            fieldName: "scenarioRunCountRequested",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "scenarioRunCountCompleted",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "scenarioRunCountFailed",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "gradeSampleCountRequested",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "gradeSampleCountCompleted",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "gradeSampleCountFailed",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "executionFailureCount",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "gradingFailureCount",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "passRate",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "scoreMin",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "scoreMedian",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "scoreMax",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Scalar",
                            fieldName: "scoreMean",
                            alias: null,
                            arguments: null,
                            isUpdatable: false,
                          },
                          {
                            kind: "Linked",
                            fieldName: "outlierScenarioRuns",
                            alias: null,
                            arguments: [
                              [
                                "first",
                                { kind: "Literal", value: 25 },
                              ],
                            ],
                            condition: null,
                            isUpdatable: false,
                            refetchQueryIndex: null,
                            selections: [
                              {
                                kind: "Linked",
                                fieldName: "edges",
                                alias: null,
                                arguments: null,
                                condition: null,
                                isUpdatable: false,
                                refetchQueryIndex: null,
                                selections: [
                                  {
                                    kind: "Linked",
                                    fieldName: "node",
                                    alias: null,
                                    arguments: null,
                                    condition: null,
                                    isUpdatable: false,
                                    refetchQueryIndex: null,
                                    selections: [
                                      {
                                        kind: "Scalar",
                                        fieldName: "key",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "scenarioRunId",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "gradeSampleCount",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "completedSampleCount",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "executionFailureCount",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "gradingFailureCount",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "averageScore",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "minScore",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "maxScore",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "failed",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "minRunId",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "maxRunId",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "messageRefId",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            kind: "Linked",
                            fieldName: "failureReasons",
                            alias: null,
                            arguments: [
                              [
                                "first",
                                { kind: "Literal", value: 25 },
                              ],
                            ],
                            condition: null,
                            isUpdatable: false,
                            refetchQueryIndex: null,
                            selections: [
                              {
                                kind: "Linked",
                                fieldName: "edges",
                                alias: null,
                                arguments: null,
                                condition: null,
                                isUpdatable: false,
                                refetchQueryIndex: null,
                                selections: [
                                  {
                                    kind: "Linked",
                                    fieldName: "node",
                                    alias: null,
                                    arguments: null,
                                    condition: null,
                                    isUpdatable: false,
                                    refetchQueryIndex: null,
                                    selections: [
                                      {
                                        kind: "Scalar",
                                        fieldName: "key",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "kind",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "reason",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                      {
                                        kind: "Scalar",
                                        fieldName: "count",
                                        alias: null,
                                        arguments: null,
                                        isUpdatable: false,
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

const artifact: EagerReaderArtifact<
  Query__EntrypointWorkspaceVerifyLiveWrite__param,
  Query__EntrypointWorkspaceVerifyLiveWrite__output_type
> = {
  kind: "EagerReaderArtifact",
  fieldName: "EntrypointWorkspaceVerifyLiveWrite",
  resolver,
  readerAst,
  hasUpdatable: false,
};

export default artifact;
