// @generated by infra/bft/tasks/routesBuild.ts
import { iso } from "@iso-gambit-sim";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
  status?: number;
  headers?: Record<string, string>;
};

iso(`entrypoint Mutation.GambitSimulatorStopRun`)
iso(`entrypoint Mutation.GambitWorkspaceBuildRunCreate`)
iso(`entrypoint Mutation.GambitWorkspaceCreate`)
iso(`entrypoint Mutation.GambitWorkspaceGradeFlagReasonUpdate`)
iso(`entrypoint Mutation.GambitWorkspaceGradeFlagToggle`)
iso(`entrypoint Mutation.GambitWorkspaceGradeRunCreate`)
iso(`entrypoint Mutation.GambitWorkspaceScenarioRunSend`)
iso(`entrypoint Mutation.GambitWorkspaceScenarioRunStart`)
iso(`entrypoint Mutation.GambitWorkspaceScenarioRunStop`)
iso(`entrypoint Mutation.GambitWorkspaceVerifyBatchRunCreate`)
iso(`entrypoint Query.EntrypointChatOptimisticPlaceholder`)
iso(`entrypoint Query.EntrypointSimulatorBuildPage`)
iso(`entrypoint Query.EntrypointSimulatorGradePage`)
iso(`entrypoint Query.EntrypointSimulatorRedirect`)
iso(`entrypoint Query.EntrypointSimulatorRoot`)
iso(`entrypoint Query.EntrypointSimulatorTestPage`)
iso(`entrypoint Query.EntrypointSimulatorVerifyPage`)
iso(`entrypoint Query.EntrypointSimulatorWorkspaceShell`)
iso(`entrypoint Query.EntrypointSimulatorWorkspaces`)
iso(`entrypoint Query.EntrypointWorkspaceBuildLiveWrite`)
iso(`entrypoint Query.EntrypointWorkspaceBuildTabLiveWrite`)
iso(`entrypoint Query.EntrypointWorkspaceGradeLiveWrite`)
iso(`entrypoint Query.EntrypointWorkspaceVerifyLiveWrite`)
iso(`entrypoint Query.EntrypointWorkspaceWorkbenchLiveWrite`)

import entrypointChatOptimisticPlaceholder from "@iso-gambit-sim/Query/EntrypointChatOptimisticPlaceholder/entrypoint.ts"
import entrypointSimulatorBuildPage from "@iso-gambit-sim/Query/EntrypointSimulatorBuildPage/entrypoint.ts"
import entrypointSimulatorGradePage from "@iso-gambit-sim/Query/EntrypointSimulatorGradePage/entrypoint.ts"
import entrypointSimulatorRedirect from "@iso-gambit-sim/Query/EntrypointSimulatorRedirect/entrypoint.ts"
import entrypointSimulatorRoot from "@iso-gambit-sim/Query/EntrypointSimulatorRoot/entrypoint.ts"
import entrypointSimulatorTestPage from "@iso-gambit-sim/Query/EntrypointSimulatorTestPage/entrypoint.ts"
import entrypointSimulatorVerifyPage from "@iso-gambit-sim/Query/EntrypointSimulatorVerifyPage/entrypoint.ts"
import entrypointSimulatorWorkspaceShell from "@iso-gambit-sim/Query/EntrypointSimulatorWorkspaceShell/entrypoint.ts"
import entrypointSimulatorWorkspaces from "@iso-gambit-sim/Query/EntrypointSimulatorWorkspaces/entrypoint.ts"
import entrypointWorkspaceBuildLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceBuildLiveWrite/entrypoint.ts"
import entrypointWorkspaceBuildTabLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceBuildTabLiveWrite/entrypoint.ts"
import entrypointWorkspaceGradeLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceGradeLiveWrite/entrypoint.ts"
import entrypointWorkspaceVerifyLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceVerifyLiveWrite/entrypoint.ts"
import entrypointWorkspaceWorkbenchLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceWorkbenchLiveWrite/entrypoint.ts"
import gambitSimulatorStopRun from "@iso-gambit-sim/Mutation/GambitSimulatorStopRun/entrypoint.ts"
import gambitWorkspaceBuildRunCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceBuildRunCreate/entrypoint.ts"
import gambitWorkspaceCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceCreate/entrypoint.ts"
import gambitWorkspaceGradeFlagReasonUpdate from "@iso-gambit-sim/Mutation/GambitWorkspaceGradeFlagReasonUpdate/entrypoint.ts"
import gambitWorkspaceGradeFlagToggle from "@iso-gambit-sim/Mutation/GambitWorkspaceGradeFlagToggle/entrypoint.ts"
import gambitWorkspaceGradeRunCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceGradeRunCreate/entrypoint.ts"
import gambitWorkspaceScenarioRunSend from "@iso-gambit-sim/Mutation/GambitWorkspaceScenarioRunSend/entrypoint.ts"
import gambitWorkspaceScenarioRunStart from "@iso-gambit-sim/Mutation/GambitWorkspaceScenarioRunStart/entrypoint.ts"
import gambitWorkspaceScenarioRunStop from "@iso-gambit-sim/Mutation/GambitWorkspaceScenarioRunStop/entrypoint.ts"
import gambitWorkspaceVerifyBatchRunCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceVerifyBatchRunCreate/entrypoint.ts"

export {entrypointChatOptimisticPlaceholder};
export {entrypointSimulatorBuildPage};
export {entrypointSimulatorGradePage};
export {entrypointSimulatorRedirect};
export {entrypointSimulatorRoot};
export {entrypointSimulatorTestPage};
export {entrypointSimulatorVerifyPage};
export {entrypointSimulatorWorkspaceShell};
export {entrypointSimulatorWorkspaces};
export {entrypointWorkspaceBuildLiveWrite};
export {entrypointWorkspaceBuildTabLiveWrite};
export {entrypointWorkspaceGradeLiveWrite};
export {entrypointWorkspaceVerifyLiveWrite};
export {entrypointWorkspaceWorkbenchLiveWrite};
export {gambitSimulatorStopRun};
export {gambitWorkspaceBuildRunCreate};
export {gambitWorkspaceCreate};
export {gambitWorkspaceGradeFlagReasonUpdate};
export {gambitWorkspaceGradeFlagToggle};
export {gambitWorkspaceGradeRunCreate};
export {gambitWorkspaceScenarioRunSend};
export {gambitWorkspaceScenarioRunStart};
export {gambitWorkspaceScenarioRunStop};
export {gambitWorkspaceVerifyBatchRunCreate};
