// @generated by infra/bft/tasks/routesBuild.ts
export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
  status?: number;
  headers?: Record<string, string>;
};

import entrypointChatOptimisticPlaceholder from "@iso-gambit-sim/Query/EntrypointChatOptimisticPlaceholder/entrypoint.ts"
import entrypointSimulatorBuildPage from "@iso-gambit-sim/Query/EntrypointSimulatorBuildPage/entrypoint.ts"
import entrypointSimulatorGradePage from "@iso-gambit-sim/Query/EntrypointSimulatorGradePage/entrypoint.ts"
import entrypointSimulatorRedirect from "@iso-gambit-sim/Query/EntrypointSimulatorRedirect/entrypoint.ts"
import entrypointSimulatorRoot from "@iso-gambit-sim/Query/EntrypointSimulatorRoot/entrypoint.ts"
import entrypointSimulatorTestPage from "@iso-gambit-sim/Query/EntrypointSimulatorTestPage/entrypoint.ts"
import entrypointSimulatorVerifyPage from "@iso-gambit-sim/Query/EntrypointSimulatorVerifyPage/entrypoint.ts"
import entrypointSimulatorWorkspaceShell from "@iso-gambit-sim/Query/EntrypointSimulatorWorkspaceShell/entrypoint.ts"
import entrypointSimulatorWorkspaces from "@iso-gambit-sim/Query/EntrypointSimulatorWorkspaces/entrypoint.ts"
import entrypointWorkspaceBuildLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceBuildLiveWrite/entrypoint.ts"
import entrypointWorkspaceBuildTabLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceBuildTabLiveWrite/entrypoint.ts"
import entrypointWorkspaceGradeLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceGradeLiveWrite/entrypoint.ts"
import entrypointWorkspaceTestLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceTestLiveWrite/entrypoint.ts"
import entrypointWorkspaceVerifyLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceVerifyLiveWrite/entrypoint.ts"
import entrypointWorkspaceWorkbenchLiveWrite from "@iso-gambit-sim/Query/EntrypointWorkspaceWorkbenchLiveWrite/entrypoint.ts"
import gambitSimulatorResetWorkspace from "@iso-gambit-sim/Mutation/GambitSimulatorResetWorkspace/entrypoint.ts"
import gambitSimulatorStopRun from "@iso-gambit-sim/Mutation/GambitSimulatorStopRun/entrypoint.ts"
import gambitWorkspaceBuildRunCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceBuildRunCreate/entrypoint.ts"
import gambitWorkspaceConversationSessionSend from "@iso-gambit-sim/Mutation/GambitWorkspaceConversationSessionSend/entrypoint.ts"
import gambitWorkspaceConversationSessionStart from "@iso-gambit-sim/Mutation/GambitWorkspaceConversationSessionStart/entrypoint.ts"
import gambitWorkspaceConversationSessionStop from "@iso-gambit-sim/Mutation/GambitWorkspaceConversationSessionStop/entrypoint.ts"
import gambitWorkspaceCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceCreate/entrypoint.ts"
import gambitWorkspaceDelete from "@iso-gambit-sim/Mutation/GambitWorkspaceDelete/entrypoint.ts"
import gambitWorkspaceFeedbackSave from "@iso-gambit-sim/Mutation/GambitWorkspaceFeedbackSave/entrypoint.ts"
import gambitWorkspaceGradeFlagReasonUpdate from "@iso-gambit-sim/Mutation/GambitWorkspaceGradeFlagReasonUpdate/entrypoint.ts"
import gambitWorkspaceGradeFlagToggle from "@iso-gambit-sim/Mutation/GambitWorkspaceGradeFlagToggle/entrypoint.ts"
import gambitWorkspaceGradeRunCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceGradeRunCreate/entrypoint.ts"
import gambitWorkspaceScenarioRunSend from "@iso-gambit-sim/Mutation/GambitWorkspaceScenarioRunSend/entrypoint.ts"
import gambitWorkspaceScenarioRunStart from "@iso-gambit-sim/Mutation/GambitWorkspaceScenarioRunStart/entrypoint.ts"
import gambitWorkspaceScenarioRunStop from "@iso-gambit-sim/Mutation/GambitWorkspaceScenarioRunStop/entrypoint.ts"
import gambitWorkspaceVerifyBatchRunCreate from "@iso-gambit-sim/Mutation/GambitWorkspaceVerifyBatchRunCreate/entrypoint.ts"

export {entrypointChatOptimisticPlaceholder};
export {entrypointSimulatorBuildPage};
export {entrypointSimulatorGradePage};
export {entrypointSimulatorRedirect};
export {entrypointSimulatorRoot};
export {entrypointSimulatorTestPage};
export {entrypointSimulatorVerifyPage};
export {entrypointSimulatorWorkspaceShell};
export {entrypointSimulatorWorkspaces};
export {entrypointWorkspaceBuildLiveWrite};
export {entrypointWorkspaceBuildTabLiveWrite};
export {entrypointWorkspaceGradeLiveWrite};
export {entrypointWorkspaceTestLiveWrite};
export {entrypointWorkspaceVerifyLiveWrite};
export {entrypointWorkspaceWorkbenchLiveWrite};
export {gambitSimulatorResetWorkspace};
export {gambitSimulatorStopRun};
export {gambitWorkspaceBuildRunCreate};
export {gambitWorkspaceConversationSessionSend};
export {gambitWorkspaceConversationSessionStart};
export {gambitWorkspaceConversationSessionStop};
export {gambitWorkspaceCreate};
export {gambitWorkspaceDelete};
export {gambitWorkspaceFeedbackSave};
export {gambitWorkspaceGradeFlagReasonUpdate};
export {gambitWorkspaceGradeFlagToggle};
export {gambitWorkspaceGradeRunCreate};
export {gambitWorkspaceScenarioRunSend};
export {gambitWorkspaceScenarioRunStart};
export {gambitWorkspaceScenarioRunStop};
export {gambitWorkspaceVerifyBatchRunCreate};
