import { type FieldNode, Kind, parse, print } from "graphql";
import * as path from "@std/path";
import { toFileUrl } from "@std/path";

const GENERATED_QUERY_TEXT_PATH = path.resolve(
  "packages/gambit/packages/gambit-simulator/simulator-ui/__generated__/__isograph/Query/EntrypointWorkspaceTestLiveWrite/query_text.ts",
);
const OUTPUT_PATH = path.resolve(
  "packages/gambit/packages/gambit-simulator/simulator-ui/subscriptions/__generated__/workspaceTestLiveSubscriptionQuery.ts",
);

async function loadEntrypointQueryText(): Promise<string> {
  const moduleUrl = toFileUrl(GENERATED_QUERY_TEXT_PATH).href;
  const mod = await import(moduleUrl);
  if (typeof mod.default !== "string" || mod.default.trim().length === 0) {
    throw new Error(
      "EntrypointWorkspaceTestLiveWrite query_text.ts did not export a query string.",
    );
  }
  return mod.default;
}

function extractWorkspaceField(queryText: string): FieldNode {
  const document = parse(queryText);
  const op = document.definitions.find((def) =>
    def.kind === Kind.OPERATION_DEFINITION
  );
  if (!op || op.kind !== Kind.OPERATION_DEFINITION) {
    throw new Error("Expected an operation definition in entrypoint query.");
  }
  const workspaceSelection = op.selectionSet.selections.find((selection) =>
    selection.kind === Kind.FIELD && selection.name.value === "workspace"
  );
  if (!workspaceSelection || workspaceSelection.kind !== Kind.FIELD) {
    throw new Error(
      "Could not find `workspace(...)` field in entrypoint query selections.",
    );
  }
  return workspaceSelection;
}

async function main() {
  const queryText = await loadEntrypointQueryText();
  const workspaceField = extractWorkspaceField(queryText);
  const workspaceWriteRootKey = workspaceField.alias?.value ??
    workspaceField.name.value;
  if (!workspaceField.selectionSet) {
    throw new Error(
      "Expected workspace field selection set in entrypoint query.",
    );
  }
  const printedWorkspaceSelectionSet = print(workspaceField.selectionSet);

  const nextQuery =
    `subscription WorkspaceTestLiveSubscription($workspaceId: ID!, $fromOffset: Int) {\n` +
    `  workspaceTestLive(workspaceId: $workspaceId, fromOffset: $fromOffset) {\n` +
    `    cursor\n` +
    `    sourceOffset\n` +
    `    occurredAt\n` +
    `    node ${printedWorkspaceSelectionSet.split("\n").join("\n    ")}\n` +
    `  }\n` +
    `}\n`;

  const output =
    `// @generated by packages/gambit/packages/gambit-simulator/simulator-ui/scripts/generate_workspace_test_live_subscription_query.ts
export const WORKSPACE_TEST_LIVE_WRITE_ROOT_KEY = ${
      JSON.stringify(workspaceWriteRootKey)
    } as const;

export const WORKSPACE_TEST_LIVE_SUBSCRIPTION_QUERY = ${
      JSON.stringify(nextQuery)
    };

export default WORKSPACE_TEST_LIVE_SUBSCRIPTION_QUERY;
`;

  await Deno.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await Deno.writeTextFile(OUTPUT_PATH, output);
}

if (import.meta.main) {
  await main();
}
